#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

STAGED_FILES=$(git diff --name-only --cached)

# Esegue Prettier su tutti i file e li formatta
npx prettier . --write

# Aggiorna la versione nel package.json senza creare un tag Git
npm version patch --no-git-tag-version

# Aggiunge il package.json modificato allo staging area di Git
git add package.json

# Riaggiunge i file che erano nello staging prima della formattazione di Prettier
echo "$STAGED_FILES" | xargs git add